Step-1 Import Libraries & Load Data

In [6]:
import pandas as pd
import numpy as np

In [7]:
df = pd.read_csv("../Data/Upi_transactions.csv")

In [8]:
print("Shape",df.shape)

Shape (10000, 17)

Step-2 Look At Data

In [9]:
df.head()

,Transaction_ID,Timestamp,Sender_ID,Receiver_ID,Amount,Merchant_Category,Transaction_Type,Location,Device_Type,UPI_Channel,Hour_of_Day,Day_of_Week,Historical_Spend_Pattern,Spend_Deviation_Ratio,Risk_Label,Anomaly_Flag,Anomaly_Reason
0,TXN100000,2026-01-01 00:03:25,U1107,R1270,711.24,Shopping,P2P,Kolkata,iOS,QR Code,0,Thursday,613.97,1.158,Low,0,Normal
1,TXN100001,2026-01-01 00:11:11,U1928,R1174,608.28,Bills,Bill Payment,Surat,Android,USSD,0,Thursday,1221.74,0.498,Low,0,Normal
2,TXN100002,2026-01-01 00:32:33,U1785,R1416,9646.80,Shopping,Bill Payment,Gurugram,Android,UPI Intent,0,Thursday,5558.97,1.735,Low,0,Normal
3,TXN100003,2026-01-01 00:51:33,U1526,R1530,1081.49,E-commerce,P2P,Lucknow,Android,UPI App,0,Thursday,1072.06,1.009,Low,0,Normal
4,TXN100004,2026-01-01 01:08:17,U1519,R1209,1127.74,Grocery,P2P,Lucknow,Android,UPI Intent,1,Thursday,1413.51,0.798,Low,0,Normal

In [10]:
df.tail()

,Transaction_ID,Timestamp,Sender_ID,Receiver_ID,Amount,Merchant_Category,Transaction_Type,Location,Device_Type,UPI_Channel,Hour_of_Day,Day_of_Week,Historical_Spend_Pattern,Spend_Deviation_Ratio,Risk_Label,Anomaly_Flag,Anomaly_Reason
9995,TXN109995,2026-06-30 22:40:16,U1565,R1132,1279.50,Healthcare,P2P,Jaipur,Android,QR Code,22,Tuesday,820.21,1.560,Low,0,Normal
9996,TXN109996,2026-06-30 22:45:22,U2196,R1130,1619.21,Food & Dining,P2P,Chennai,iOS,UPI App,22,Tuesday,1841.35,0.879,Low,0,Normal
9997,TXN109997,2026-06-30 23:14:57,U1423,R1298,157.36,Food & Dining,P2P,Gurugram,iOS,QR Code,23,Tuesday,359.75,0.437,Low,0,Normal
9998,TXN109998,2026-06-30 23:36:21,U1678,R1285,1165.38,E-commerce,P2P,Indore,Android,QR Code,23,Tuesday,1118.57,1.042,Low,0,Normal
9999,TXN109999,2026-06-30 23:46:15,U1738,R1384,1244.49,Food & Dining,Bill Payment,Delhi,Android,UPI App,23,Tuesday,1542.83,0.807,Low,0,Normal

In [11]:
df.sample(5, random_state=42)

,Transaction_ID,Timestamp,Sender_ID,Receiver_ID,Amount,Merchant_Category,Transaction_Type,Location,Device_Type,UPI_Channel,Hour_of_Day,Day_of_Week,Historical_Spend_Pattern,Spend_Deviation_Ratio,Risk_Label,Anomaly_Flag,Anomaly_Reason
6252,TXN106252,2026-04-25 05:06:24,U1330,R1330,948.75,E-commerce,P2M,Gurugram,Android,UPI Lite,5,Saturday,1095.45,0.866,Low,0,Normal
4684,TXN104684,2026-03-27 11:11:36,U1620,R1505,366.68,Grocery,P2M,Ahmedabad,Android,UPI Intent,11,Friday,458.99,0.799,Low,0,Normal
1731,TXN101731,2026-02-02 06:37:18,U2084,R1265,1522.30,Entertainment,P2P,Noida,Android,UPI App,6,Monday,2223.21,0.685,Low,0,Normal
4742,TXN104742,2026-03-28 12:33:34,U1513,R1035,755.74,Grocery,P2P,Chennai,Android,QR Code,12,Saturday,578.76,1.306,Low,0,Normal
4521,TXN104521,2026-03-24 07:07:45,U1837,R1707,1438.30,E-commerce,P2P,Hyderabad,Android,UPI App,7,Tuesday,911.79,1.577,Medium,0,Normal

Step 3- Dataset Structure

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Transaction_ID            10000 non-null  object
 1   Timestamp                 10000 non-null  object
 2   Sender_ID                 10000 non-null  object
 3   Receiver_ID               10000 non-null  object
 4   Amount                    10000 non-null  float64
 5   Merchant_Category         10000 non-null  object
 6   Transaction_Type          10000 non-null  object
 7   Location                  10000 non-null  object
 8   Device_Type               10000 non-null  object
 9   UPI_Channel               10000 non-null  object
 10  Hour_of_Day               10000 non-null  int64
 11  Day_of_Week               10000 non-null  object
 12  Historical_Spend_Pattern  10000 non-null  float64
 13  Spend_Deviation_Ratio     10000 non-null  float64
 14  Risk_Label                10000 non-null  object
 15  Anomaly_Flag              10000 non-null  int64
 16  Anomaly_Reason            10000 non-null  object
dtypes: float64(3), int64(2), object(12)
memory usage: 1.3+ MB

Step 4 -Columns Cheak

In [13]:
df.columns.tolist()

['Transaction_ID',
 'Timestamp',
 'Sender_ID',
 'Receiver_ID',
 'Amount',
 'Merchant_Category',
 'Transaction_Type',
 'Location',
 'Device_Type',
 'UPI_Channel',
 'Hour_of_Day',
 'Day_of_Week',
 'Historical_Spend_Pattern',
 'Spend_Deviation_Ratio',
 'Risk_Label',
 'Anomaly_Flag',
 'Anomaly_Reason']

Step 5- Missing Value

In [14]:
missing_value = df.isnull().sum()
missing_value

Transaction_ID              0
Timestamp                   0
Sender_ID                   0
Receiver_ID                 0
Amount                      0
Merchant_Category           0
Transaction_Type            0
Location                    0
Device_Type                 0
UPI_Channel                 0
Hour_of_Day                 0
Day_of_Week                 0
Historical_Spend_Pattern    0
Spend_Deviation_Ratio       0
Risk_Label                  0
Anomaly_Flag                0
Anomaly_Reason              0
dtype: int64

Step 6 -Duplicate Cheak

Complete duplicate rows

In [15]:
duplicate_rows =df.duplicated().sum()
print("Duplicate rows",duplicate_rows)

Duplicate rows 0

Transaction ID duplicates

In [16]:
duplicate_transactions = df["Transaction_ID"].duplicated().sum()
print("Duplicate Transaction",duplicate_transactions)

Duplicate Transaction 0

Step 7 - Data Type

In [17]:
df.dtypes

Transaction_ID               object
Timestamp                    object
Sender_ID                    object
Receiver_ID                  object
Amount                      float64
Merchant_Category            object
Transaction_Type             object
Location                     object
Device_Type                  object
UPI_Channel                  object
Hour_of_Day                   int64
Day_of_Week                  object
Historical_Spend_Pattern    float64
Spend_Deviation_Ratio       float64
Risk_Label                   object
Anomaly_Flag                  int64
Anomaly_Reason               object
dtype: object

In [18]:
print(df["Timestamp"].dtype)
print(df["Amount"].dtype)

object
float64

Step 8 - Convert Timestamp data type Onject To datetime

In [19]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
print(df["Timestamp"].dtype)

datetime64[ns]

Step 9 -Amount Validation

In [20]:
df["Amount"] =pd.to_numeric(df["Amount"],errors ="coerce")

In [21]:
print(df["Amount"].describe())

count     10000.000000
mean       1549.603755
std        2722.716528
min          26.400000
25%         497.595000
50%         919.505000
75%        1690.802500
max      104016.230000
Name: Amount, dtype: float64

Negative

In [22]:
print("Negative Amounts:",(df["Amount"] < 0).sum())

Negative Amounts: 0

Zero

In [23]:
print("Zero amounts:",(df["Amount"] == 0).sum())

Zero amounts: 0

Step 10 - Categorical Values Cheak

In [24]:
categorical_columns = [
    "Merchant_Category",
    "Transaction_Type",
    "Location",
    "Device_Type",
    "UPI_Channel",
    "Day_of_Week"
]
for col in categorical_columns:
    print(df[col].unique())

['Shopping' 'Bills' 'E-commerce' 'Grocery' 'Utilities' 'Fuel' 'Education'
 'Entertainment' 'Travel' 'Food & Dining' 'Healthcare'
 'Financial Services']
['P2P' 'Bill Payment' 'Recharge' 'Online Purchase' 'P2M']
['Kolkata' 'Surat' 'Gurugram' 'Lucknow' 'Jaipur' 'Bhopal' 'Noida' 'Mumbai'
 'Bengaluru' 'Indore' 'Chennai' 'Ahmedabad' 'Pune' 'Delhi' 'Hyderabad']
['iOS' 'Android' 'Web']
['QR Code' 'USSD' 'UPI Intent' 'UPI App' 'UPI Lite']
['Thursday' 'Friday' 'Saturday' 'Sunday' 'Monday' 'Tuesday' 'Wednesday']

In [25]:
for col in categorical_columns:
    print(df[col].value_counts())

Merchant_Category
Grocery               1325
Food & Dining         1175
Shopping              1120
E-commerce            1053
Utilities             1007
Fuel                   828
Travel                 725
Bills                  702
Healthcare             607
Entertainment          568
Education              487
Financial Services     403
Name: count, dtype: int64
Transaction_Type
P2P                3008
P2M                2971
Bill Payment       1538
Online Purchase    1482
Recharge           1001
Name: count, dtype: int64
Location
Delhi        733
Lucknow      709
Kolkata      692
Indore       692
Gurugram     674
Bhopal       674
Noida        668
Ahmedabad    667
Surat        665
Pune         664
Chennai      659
Hyderabad    653
Jaipur       624
Bengaluru    614
Mumbai       612
Name: count, dtype: int64
Device_Type
Android    7169
iOS        2323
Web         508
Name: count, dtype: int64
UPI_Channel
UPI App       4241
QR Code       3159
UPI Intent    1483
UPI Lite       808
USSD           309
Name: count, dtype: int64
Day_of_Week
Thursday     1472
Tuesday      1455
Monday       1450
Friday       1433
Sunday       1428
Wednesday    1386
Saturday     1376
Name: count, dtype: int64

Step 11 - ID Validation

In [26]:
print("Unique Sender Ids:",df["Sender_ID"].nunique())
print("Unique Reciver IDs:",df["Receiver_ID"].nunique())

Unique Sender Ids: 1200
Unique Reciver IDs: 800

Missing IDs

In [27]:
print("Missing Sender IDs:",df["Sender_ID"].isna().sum())
print("Missing Reciver IDs:",df["Receiver_ID"].isna().sum())

Missing Sender IDs: 0
Missing Reciver IDs: 0

Step 12 -Time Features Validation

In [28]:
df["Hour_of_Day"] =df["Timestamp"].dt.hour
df["Day_of_Week"] =df["Timestamp"].dt.day_name()

In [29]:
df["Is_Weekend"] = (df["Timestamp"].dt.dayofweek >= 5).astype(int)

In [30]:
df[[
    "Timestamp",
    "Hour_of_Day",
    "Day_of_Week",
    "Is_Weekend"
]].head()

            Timestamp  Hour_of_Day Day_of_Week  Is_Weekend
0 2026-01-01 00:03:25            0    Thursday           0
1 2026-01-01 00:11:11            0    Thursday           0
2 2026-01-01 00:32:33            0    Thursday           0
3 2026-01-01 00:51:33            0    Thursday           0
4 2026-01-01 01:08:17            1    Thursday           0

In [31]:
df[[
    "Timestamp",
    "Hour_of_Day",
    "Day_of_Week",
    "Is_Weekend"
]].sample(5,random_state=10)

               Timestamp  Hour_of_Day Day_of_Week  Is_Weekend
937  2026-01-19 08:39:39            8      Monday           0
9355 2026-06-19 09:33:02            9      Friday           0
2293 2026-02-11 22:31:35           22   Wednesday           0
192  2026-01-04 09:35:50            9      Sunday           1
8675 2026-06-07 13:59:15           13      Sunday           1

Step 13 - Final data Quantity Summary

In [32]:
print("DATA QUANTITY SUMMARY")
print()

print("Rows:", len(df))
print("Columns:", len(df.columns))
print()

print("Duplicate Rows:", df.duplicated().sum())
print("Duplicate Transactions IDs:", df["Transaction_ID"].duplicated().sum())
print()

print("Missing Values:")
print(df.isnull().sum())
print()

print("Invalid Timestamp:", df["Timestamp"].isna().sum())
print()

print("Negative Amounts:", (df["Amount"] < 0).sum())
print("Zero Amount:", (df["Amount"] == 0).sum())

DATA QUANTITY SUMMARY

Rows: 10000
Columns: 18

Duplicate Rows: 0
Duplicate Transactions IDs: 0

Missing Values:
Transaction_ID              0
Timestamp                   0
Sender_ID                   0
Receiver_ID                 0
Amount                      0
Merchant_Category           0
Transaction_Type            0
Location                    0
Device_Type                 0
UPI_Channel                 0
Hour_of_Day                 0
Day_of_Week                 0
Historical_Spend_Pattern    0
Spend_Deviation_Ratio       0
Risk_Label                  0
Anomaly_Flag                0
Anomaly_Reason              0
Is_Weekend                  0
dtype: int64

Invalid Timestamp: 0

Negative Amounts: 0
Zero Amount: 0

Cleaned Datset Saved

In [34]:
df.to_csv("../data/Processed/Upi_transactions_cleaned.csv", index=False)